### ISSUE TITLE
出现解析安装失败

### ISSUE THREAD

**Issue by LingCn** [heynchy/eros-plugin-filecache-manager#1]
调用预览文件方法安装APP，有一台手机出现解析安装失败，有可能是什么原因呢？

**Comment by heynchy** [comment]
1. 首先确认的的预览文件的方法是没有问题的，因为安装包已经下载完成
2. 你需要确认一下安装包有没有问题
3. 如果安装包没有问题的话，看一下安装包的签名文件是否一致
4. 如果仅有一台手机出现异常，而其他手机安装成功，可判定为手机问题
5. 如果是手机问题：
   5.1  可能的原因就是APP安装包对应的sdk版本是否符合手机系统的要求；
   5.2   如果在Android 8.0以上的手机进行APK安装时，需要安装权限：
       ` <uses-permission android:name="android.permission.REQUEST_INSTALL_PACKAGES" />`
基本上可能的原因就是以上这些

**Comment by LingCn** [comment]
谢谢提供的参考
