### ISSUE TITLE
报错了，缓存模块报错

### ISSUE THREAD

**Issue by akFace** [heynchy/eros-plugin-filecache-manager#2]
如图：
getCachesSize和clearCaches都闪退

![qq 20190114181125](https://user-images.githubusercontent.com/22288837/51106813-d3570f00-1827-11e9-95b8-82a6ca0c1c14.png)

**Comment by akFace** [comment]
![image](https://user-images.githubusercontent.com/22288837/51106870-0b5e5200-1828-11e9-89f6-2b35dec8dd61.png)

**Comment by heynchy** [comment]
如果可以，请提供完整的log信息

**Comment by akFace** [comment]
试了其他的，跳转应用市场是可以用的，

这是清除缓存报的错
![image](https://user-images.githubusercontent.com/22288837/51231486-9a8d7600-199e-11e9-9067-f21e6b18b681.png)
![image](https://user-images.githubusercontent.com/22288837/51231759-7da57280-199f-11e9-94c4-79279331274d.png)


看了你的源码的这两个对比
![image](https://user-images.githubusercontent.com/22288837/51234093-ba289c80-19a6-11e9-8086-aad3e01d7ecc.png)
是不是少加了 final导致的啊，我也不太懂Java  :joy:
![image](https://user-images.githubusercontent.com/22288837/51234115-cdd40300-19a6-11e9-873d-c877fe2d7f05.png)

**Comment by akFace** [comment]
日志文本， [log.txt](https://github.com/heynchy/eros-plugin-filecache-manager/files/2762989/log.txt)

**Comment by heynchy** [comment]
请问您用的wxframework包的版本是多少？

（当前工具类支持--基础依赖包wxframework <= 1.0.9 的版本
如果您的基础依赖包wxframework的版本 > 1.0.9 , 为了使该工具类继续可以使用， 可前往: Eros-plugin-android-extend）

从log来看应该是wxframework的版本 > 1.0.9
你可以试试：
将：
implementation 'com.github.heynchy:eros-plugin-filecache-manager:0.1.4'
替换为
 implementation 'com.github.heynchy:eros-plugin-android-extend:v0.1.4'

如果编译报错， clean 一下就好； 如果还报错的话，请提供相关的log信息，再分析分析

**Comment by akFace** [comment]
OK了，多谢！
真是抱歉！我把这个wxframework <= 1.0.9
错看成了 weexSDK < 0.19.0 了    😂 😂 😂

**Comment by heynchy** [comment]
客气
